"""empty message

Revision ID: 5326852482bf
Revises: 1a7bfab8c116
Create Date: 2020-10-31 23:56:00.171445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5326852482bf'
down_revision = '1a7bfab8c116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('meetings',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('set_duration', sa.Interval(), nullable=True),
    sa.Column('final_duration', sa.Interval(), nullable=True),
    sa.Column('set_start_time', sa.Time(), nullable=True),
    sa.Column('set_end_time', sa.Time(), nullable=True),
    sa.Column('final_start_time', sa.Time(), nullable=True),
    sa.Column('final_end_time', sa.Time(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meeting_name')
    )
    op.create_table('agendas',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_name', sa.String(length=255), nullable=False),
    sa.Column('set_duration', sa.Interval(), nullable=False),
    sa.Column('final_duration', sa.Interval(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'agenda_name')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('is_superuser IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('agendas')
    op.drop_table('meetings')
    op.drop_table('users')
    # ### end Alembic commands ###
