"""empty message

Revision ID: b56fec8e88cd
Revises: 5326852482bf
Create Date: 2020-11-01 00:56:37.664576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56fec8e88cd'
down_revision = '5326852482bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meeting_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'meeting_date')
    # ### end Alembic commands ###
